name: arb
description: Arb file parser for dart and flutter.
version: 0.0.4
author: 'Jaime <git@jaimeblasco.com>'
homepage: 'https://github.com/jamesblasco/dart_arb'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  path: ^1.6.4



